final List<Map<String, String>> newInternationalBooks = [
  {
    "id": "GEN",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Gen",
    "name": "Genesis",
    "nameLong": "The First Book of Moses, called Genesis",
    "imageUrl": "https://example.com/images/genesis.jpg",
  },
  {
    "id": "EXO",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Exo",
    "name": "Exodus",
    "nameLong": "The Second Book of Moses, called Exodus",
    "imageUrl": "https://example.com/images/exodus.jpg",
  },
  {
    "id": "LEV",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Lev",
    "name": "Leviticus",
    "nameLong": "The Third Book of Moses, called Leviticus",
    "imageUrl": "https://example.com/images/leviticus.jpg",
  },
  {
    "id": "NUM",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Num",
    "name": "Numbers",
    "nameLong": "The Fourth Book of Moses, called Numbers",
    "imageUrl": "https://example.com/images/numbers.jpg",
  },
  {
    "id": "DEU",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Deu",
    "name": "Deuteronomy",
    "nameLong": "The Fifth Book of Moses, called Deuteronomy",
    "imageUrl": "https://example.com/images/deuteronomy.jpg",
  },
  {
    "id": "JOS",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Jos",
    "name": "Joshua",
    "nameLong": "The Book of Joshua",
    "imageUrl": "https://example.com/images/joshua.jpg",
  },
  {
    "id": "JDG",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Jdg",
    "name": "Judges",
    "nameLong": "The Book of Judges",
    "imageUrl": "https://example.com/images/judges.jpg",
  },
  {
    "id": "RUT",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "Rut",
    "name": "Ruth",
    "nameLong": "The Book of Ruth",
    "imageUrl": "https://example.com/images/ruth.jpg",
  },
  {
    "id": "1SA",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "1Sa",
    "name": "1 Samuel",
    "nameLong": "The First Book of Samuel",
    "imageUrl": "https://example.com/images/1samuel.jpg",
  },
  {
    "id": "2SA",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "2Sa",
    "name": "2 Samuel",
    "nameLong": "The Second Book of Samuel",
    "imageUrl": "https://example.com/images/2samuel.jpg",
  },
  {
    "id": "1KI",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "1Ki",
    "name": "1 Kings",
    "nameLong": "The First Book of Kings",
    "imageUrl": "https://example.com/images/1kings.jpg",
  },
  {
    "id": "2KI",
    "bibleId": "de4e12af7f28f599-01",
    "abbreviation": "2Ki",
    "name": "2 Kings",
    "nameLong": "The Second Book of Kings",
    "imageUrl": "https://example.com/images/2kings.jpg",
  }
];
